### PR TITLE
Accessibility development

### PR DESCRIPTION
**Pull request by inakiesk**
This review request is for the following members:
-Iñaki Eskauriatza Ruiz
-Ademola Owoeye

This branch is dedicated to fixing any accessibility issues that the website may have based on WAI standards. Our findings and changes were the following:
**-Page titles:** Page title was already implemented. No changes required.
**-Image text alternatives:** Alt text was modified for all images to have a more specific description.
**-Text headings:** All sections had heading tags already included. No changes required.
**-Color contrast:** Contrast filter added to several pieces of text for better readability.
**-Resize:** Heights, widths and positioning were modified for better responsiveness to allow font size to be increased without elements of the website overlapping.
**-Interaction:** Labels added to the inputs in the form section as suggested for the voice-over tools without being displayed to keep the website similar to the template.
**-Moving content:** There is no moving, blinking or scrolling information that lasts for more than five seconds on this website. No changes required.
**-Multimedia:** There is no video or audio content on this website. No changes required.
**-Basic structure:** Website has basic structure and allows to properly read and understand the order of the information.

### CODE REVIEW

**Review by roshan-bajgain — CHANGES_REQUESTED** [review]
Hi @inakiesk, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️

- [ ] I would suggest you add `Mark's portfolio
Mark full-stack web developer` for a better page title in place of Mark you can use your name.

- [ ] Your page is scrolling horizontally kindly fix it as well

### Your design

hhhh

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by inakiesk** [comment]
Summary of new changes:
-Finally fixed mysterious extra white space issue. (took me hours to find)
-Updated the website's title to make it more descriptive as suggested, but did not make it too long as specified by WAI standards.

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi @inakiesk , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] As the previous reviewer said your page is scrolling horizontally kindly fix it.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by inakiesk** [comment]
Hello, @ShahierNashaat 
I am sorry, can you elaborate where you see the horizontal scroll? I just checked and I have not been able to see any horizontal scrolling, even when I zoom in, it appears to be adapting correctly on my end.
image

I would really appreciate some feedback on this because I do not know why it is displaying correctly (without horizontal scrollbar) on my end.

**Comment by ShahierNashaat** [comment]
Hi, @inakiesk I don't know can't see the horizontal scroll but I guess you can fix that by using the percentage `%` when you assign a width in CSS instead of `vw` ie: `width: 100%`.

Screenshot from 2022-07-14 01-55-18

**Comment by inakiesk** [comment]
> Hello, @ShahierNashaat I am sorry, can you elaborate where you see the horizontal scroll? I just checked and I have not been able to see any horizontal scrolling, even when I zoom in, it appears to be adapting correctly on my end. image
> 
> I would really appreciate some feedback on this because I do not know why it is displaying correctly (without horizontal scrollbar) on my end.

Just noticed through the outline about the issue! Working on it right now.
image

**Review by Ismailco — APPROVED** [review]
### Hi @inakiesk, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

cr-approve


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
